# Generated by Django 2.0 on 2019-01-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=136, null=True),
        ),
    ]
